pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build, Test, and Package') {
            steps {
                dir('WebApplicationIntegration') {
                    sh 'mvn package'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }
}